services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: my_usr
      POSTGRES_PASSWORD: my_pwd
      POSTGRES_DB: codeck
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=my_user
      - DB_PASSWORD=my_pwd
      - DB_NAME=codeck
    depends_on:
      - db

volumes:
  postgres_data:
