// @title CODECK API
// @version 1.0
// @description API for CODECK - COmpetição DE Código do Kim. A platform for competitive programmers.

// @license.name MIT

// @host localhost:8080
// @BasePath /
// @schemes http https

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

package main

import (
	"fmt"
	"log"
	"net/http"
	"os"

	"backend/controllers"
	"backend/utils"

	"backend/models/activity"
	"backend/models/comment"
	"backend/models/group"
	"backend/models/user"

	"backend/routes"

	_ "backend/docs" // docs is generated by swag init command

	"github.com/gorilla/mux"
	"github.com/rs/cors"
	httpSwagger "github.com/swaggo/http-swagger"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

// getEnv gets an environment variable or returns a default value
func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}

func main() {
	// Initialize upload directory
	if err := utils.InitUploadDirs(); err != nil {
		log.Fatalf("Failed to initialize upload directory: %v", err)
	}

	r := mux.NewRouter()

	// Add static file serving for uploaded images
	r.PathPrefix("/uploads/").Handler(http.StripPrefix("/uploads/", http.FileServer(http.Dir("uploads/"))))

	// Add Swagger endpoint
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)
	// Migrate db
	log.Println("Trying to migrate")

	// Get database configuration from environment variables with defaults
	dbHost := getEnv("DB_HOST", "db")
	dbPort := getEnv("DB_PORT", "5432")
	dbUser := getEnv("DB_USER", "my_usr")
	dbPassword := getEnv("DB_PASSWORD", "my_pwd")
	dbName := getEnv("DB_NAME", "codeck")

	dsn := fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=%s sslmode=disable",
		dbHost, dbUser, dbPassword, dbName, dbPort)

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		log.Fatalf("Failed to connect to the database: %v", err)
	}
	if err := db.AutoMigrate(&group.Group{}, &group.GroupMember{}, &group.GroupInvite{}, &activity.Activity{}, &activity.ActivityGroup{}, &comment.Comment{}, &user.User{}); err != nil {
		log.Fatalf("Failed to migrate database: %v", err)
	}
	log.Println("Migration successful")

	group.DefaultGroupModel = group.NewGormGroupModel(db)
	activity.DefaultActivityModel = activity.NewGormActivityModel(db)
	user.DefaultUserModel = user.NewGormUserModel(db)
	comment.DefaultCommentModel = comment.NewGormCommentModel(db)

	groupController := controllers.NewGroupController(group.DefaultGroupModel, activity.DefaultActivityModel, user.DefaultUserModel)
	activityController := controllers.NewActivityController(activity.DefaultActivityModel, group.DefaultGroupModel)
	userController := controllers.NewUserController(user.DefaultUserModel, activity.DefaultActivityModel, group.DefaultGroupModel)
	loginController := controllers.NewLoginController(user.DefaultUserModel)
	commentController := controllers.NewCommentController(comment.DefaultCommentModel, activity.DefaultActivityModel, group.DefaultGroupModel)

	routes.RegisterGroupRoutes(r, groupController)
	routes.RegisterActivityRoutes(r, activityController)
	routes.RegisterUserRoutes(r, userController)
	routes.RegisterLoginRoutes(r, loginController)
	routes.RegisterCommentRoutes(r, commentController)

	// Configure CORS
	c := cors.New(cors.Options{
		AllowedOrigins: []string{
			"http://localhost:3000", // React development server
			"http://127.0.0.1:3000", // Alternative localhost
			"http://localhost:3001", // Alternative React port
		},
		AllowedMethods: []string{
			http.MethodGet,
			http.MethodPost,
			http.MethodPut,
			http.MethodDelete,
			http.MethodOptions,
		},
		AllowedHeaders: []string{
			"Origin",
			"Content-Type",
			"Accept",
			"Authorization",
			"X-Requested-With",
		},
		AllowCredentials: true,
	})

	// Wrap the router with CORS middleware
	handler := c.Handler(r)

	log.Println("Server is running on port 8080")
	log.Println("API Documentation available at: http://localhost:8080/swagger/index.html")
	log.Fatal(http.ListenAndServe(":8080", handler))

}
