// @title CODECK API
// @version 1.0
// @description API for CODECK - COmpetição DE Código do Kim. A platform for competitive programmers.

// @license.name MIT

// @host localhost:8080
// @BasePath /
// @schemes http https

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.

package main

import (
	"log"
	"net/http"

	"backend/controllers"

	"backend/models/activity"
	"backend/models/group"
	"backend/models/user"

	"backend/routes"

	_ "backend/docs" // docs is generated by swag init command

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

func main() {
	r := mux.NewRouter()

	groupController := controllers.NewGroupController(group.DefaultGroupModel)
	activityController := controllers.NewActivityController(activity.DefaultActivityModel)
	userController := controllers.NewUserController(user.DefaultUserModel, activity.DefaultActivityModel)
	loginController := controllers.NewLoginController(user.DefaultUserModel)

	routes.RegisterGroupRoutes(r, groupController)
	routes.RegisterActivityRoutes(r, activityController)
	routes.RegisterUserRoutes(r, userController)
	routes.RegisterLoginRoutes(r, loginController)

	// Add Swagger endpoint
	r.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	log.Println("Server is running on port 8080")
	log.Println("API Documentation available at: http://localhost:8080/swagger/index.html")
	log.Fatal(http.ListenAndServe(":8080", r))
}
